name: Python Project Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build and test
        run: python3 -m unittest

      - name: Kill existing process
        run: |
          ps aux | grep autotrade.py
          sudo pkill -f autotrade.py

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} #instance IP
          username: ${{ secrets.EC2_USER }} # ubuntu id
          key: ${{ secrets.EC2_KEY }} # ec2 instance pem key
          script: |
            sudo systemctl stop autotrade.service
            cd /home/ubuntu/gpt-bitcoin
            git pull origin main
            pip3 install -r requirements.txt
            sudo systemctl start autotrade.service
